"""The ParaBank login page.

Selectors come from docs/sut-ui-elements.md, generated by scripts/discover_ui.py
against the running application. None of them is guessed.

    input[name='username']
    input[name='password']
    input[type='submit'][value='Log In']

A note on selector choice. Playwright's preferred locators are user-facing ones
such as get_by_label, because they survive markup changes and assert the same
thing a screen reader sees. They are not usable here: ParaBank's login inputs
carry no id attribute, so no label can be associated with them programmatically.

That is not a limitation of the framework. It is the accessibility defect that
TC-ACC-004 exists to find, discovered before the accessibility phase began.
"""

from __future__ import annotations

from pages.base_page import BasePage


class LoginPage(BasePage):
    path = "/index.htm"

    USERNAME = "input[name='username']"
    PASSWORD = "input[name='password']"
    SUBMIT = "input[type='submit'][value='Log In']"

    def log_in_as(self, username: str, password: str) -> None:
        """Fill the form and submit it. Says nothing about whether it worked."""
        self.page.fill(self.USERNAME, username)
        self.page.fill(self.PASSWORD, password)
        self.page.click(self.SUBMIT)
        self.page.wait_for_load_state("networkidle")

    def submit_empty(self, username: str = "", password: str = "") -> None:
        """Submit with either or both fields blank, for the boundary cases."""
        self.page.fill(self.USERNAME, username)
        self.page.fill(self.PASSWORD, password)
        self.page.click(self.SUBMIT)
        self.page.wait_for_load_state("networkidle")

    def is_displayed(self) -> bool:
        return self.page.locator(self.USERNAME).count() > 0
