"""Record the real shape of ParaBank's API responses.

The endpoint paths came from the service description in Phase 1. The shape of
what each endpoint returns did not, and assertions must never be written
against a guessed shape.

This script calls the key endpoints and writes docs/sut-api-shapes.md with the
status, content type, and structure of each response. Phase 3B's tests are
written from that file.

It performs one transfer of one cent between two of the demo customer's
accounts, because the shape of a transfer response cannot be learned without
making one. That is recorded in the output rather than hidden.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from utils.api_client import ApiClient  # noqa: E402
from utils.config import get_settings  # noqa: E402
from utils.logger import get_logger  # noqa: E402

log = get_logger("discover_api_shapes")

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "sut-api-shapes.md"


def describe(value: Any, indent: int = 0) -> list[str]:
    """Describe a parsed JSON value as field names and types, not values."""
    pad = "  " * indent
    lines: list[str] = []
    if isinstance(value, dict):
        for key, val in value.items():
            if isinstance(val, (dict, list)):
                lines.append(f"{pad}{key}:")
                lines.extend(describe(val, indent + 1))
            else:
                lines.append(f"{pad}{key}: {type(val).__name__}")
    elif isinstance(value, list):
        lines.append(f"{pad}list of {len(value)} item(s)")
        if value:
            lines.append(f"{pad}first item:")
            lines.extend(describe(value[0], indent + 1))
    else:
        lines.append(f"{pad}{type(value).__name__}")
    return lines


def section(title: str, call: str, response) -> list[str]:
    lines = [
        f"## {title}",
        "",
        f"    call:         {call}",
        f"    status:       {response.status_code}",
        f"    content type: {response.headers.get('content-type', 'not stated')}",
        "",
    ]
    text = (response.text or "").strip()
    if not text:
        lines += ["Empty response body.", ""]
        return lines
    try:
        parsed = json.loads(text)
    except json.JSONDecodeError:
        preview = text[:300].replace("\n", " ")
        lines += ["Body is not JSON. First 300 characters:", "", f"    {preview}", ""]
        return lines
    lines += ["Structure:", "", "```"]
    lines += describe(parsed)
    lines += ["```", "", "Example (first 400 characters of the raw body):", "",
              "```", text[:400], "```", ""]
    return lines


def main() -> int:
    settings = get_settings()
    api = ApiClient(settings)
    out: list[str] = [
        "# ParaBank API response shapes (generated)",
        "",
        "Generated by scripts/discover_api_shapes.py against a running instance.",
        "Do not edit by hand. Re-run the script instead.",
        "",
        "Structures show field names and types, not values, so this file does not",
        "go stale every time the seeded data changes.",
        "",
    ]

    login = api.login(settings.sut.username, settings.sut.password)
    out += section("Login", f"GET /login/{settings.sut.username}/(password)", login)

    customer_id = None
    try:
        payload = login.json()
        if isinstance(payload, dict):
            customer_id = payload.get("id")
    except Exception:  # noqa: BLE001
        pass

    if customer_id is None:
        log.error("Could not read a customer identifier from the login response.")
        log.error("Writing what we have so far so the shapes are still recorded.")
        OUTPUT.write_text("\n".join(out))
        return 1

    log.info("Customer identifier from login: %s", customer_id)
    out += [f"Customer identifier read from the login response: `{customer_id}`", ""]

    accounts = api.customer_accounts(customer_id)
    out += section("Customer accounts", f"GET /customers/{customer_id}/accounts", accounts)

    account_ids: list[Any] = []
    try:
        data = accounts.json()
        if isinstance(data, list):
            account_ids = [a.get("id") for a in data if isinstance(a, dict)]
    except Exception:  # noqa: BLE001
        pass

    if len(account_ids) < 2:
        log.error("Fewer than two accounts found, cannot continue discovery.")
        OUTPUT.write_text("\n".join(out))
        return 1

    first, second = account_ids[0], account_ids[1]
    out += section("Single account", f"GET /accounts/{first}", api.account(first))
    out += section("Account transactions", f"GET /accounts/{first}/transactions",
                   api.account_transactions(first))

    log.info("Performing one transfer of 0.01 from %s to %s to learn the response shape",
             first, second)
    transfer = api.transfer(first, second, "0.01")
    out += section("Transfer", f"POST /transfer  from={first} to={second} amount=0.01", transfer)
    out += ["> This discovery run performed one real transfer of one cent between two",
            "> of the demo customer's own accounts, because the response shape cannot",
            "> be learned without making one. Recorded here rather than hidden.", ""]

    out += section("Non-existent account", "GET /accounts/99999999", api.account(99999999))

    OUTPUT.write_text("\n".join(out))
    log.info("Wrote %s", OUTPUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
