"""Record the real structure of ParaBank's pages.

Page objects must be written against selectors that actually exist. This script
opens each page in a real browser, extracts the forms, inputs, selects, buttons
and headings, and writes docs/sut-ui-elements.md.

Same principle as the endpoint and API shape discovery: the documentation comes
from the running application rather than from memory, so a page object is never
built on a guessed selector.

It logs in with the demo customer to reach the authenticated pages, and does not
submit any form that moves money.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from playwright.sync_api import sync_playwright  # noqa: E402

from utils.config import get_settings  # noqa: E402
from utils.logger import get_logger  # noqa: E402

log = get_logger("discover_ui")

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "sut-ui-elements.md"

EXTRACT = """
() => {
  const clean = (s) => (s || '').replace(/\\s+/g, ' ').trim();
  return {
    title: document.title,
    url: location.pathname + location.search,
    headings: Array.from(document.querySelectorAll('h1, h1.title, h2'))
      .map(h => clean(h.textContent)).filter(Boolean).slice(0, 6),
    forms: Array.from(document.querySelectorAll('form')).map(f => ({
      id: f.id || null,
      name: f.getAttribute('name'),
      action: f.getAttribute('action'),
      method: (f.getAttribute('method') || 'get').toUpperCase()
    })),
    inputs: Array.from(document.querySelectorAll('input')).map(i => ({
      tag: 'input',
      type: i.type,
      name: i.getAttribute('name'),
      id: i.id || null,
      value: i.type === 'submit' || i.type === 'button' ? i.value : null
    })),
    selects: Array.from(document.querySelectorAll('select')).map(s => ({
      tag: 'select',
      name: s.getAttribute('name'),
      id: s.id || null,
      options: s.options.length
    })),
    buttons: Array.from(document.querySelectorAll('button')).map(b => ({
      tag: 'button',
      type: b.type,
      id: b.id || null,
      text: clean(b.textContent)
    })),
    links: Array.from(document.querySelectorAll('a[href]'))
      .map(a => ({ text: clean(a.textContent), href: a.getAttribute('href') }))
      .filter(a => a.text).slice(0, 25),
    errors: Array.from(document.querySelectorAll('.error, .error p, span.error'))
      .map(e => clean(e.textContent)).filter(Boolean).slice(0, 5)
  };
}
"""


def render(info: dict, label: str) -> list[str]:
    lines = [f"## {label}", "", f"    path:  {info['url']}", f"    title: {info['title']}", ""]

    if info["headings"]:
        lines += ["Headings:", ""]
        lines += [f"    {h}" for h in info["headings"]]
        lines.append("")

    if info["forms"]:
        lines += ["Forms:", "", "| id | name | method | action |", "| --- | --- | --- | --- |"]
        for f in info["forms"]:
            lines.append(f"| {f['id'] or '-'} | {f['name'] or '-'} | {f['method']} | {f['action'] or '-'} |")
        lines.append("")

    fields = info["inputs"] + info["selects"]
    if fields:
        lines += ["Fields:", "", "| tag | type | name | id | detail |", "| --- | --- | --- | --- | --- |"]
        for f in fields:
            detail = f.get("value") or (f"{f['options']} options" if f.get("options") is not None else "")
            lines.append(
                f"| {f['tag']} | {f.get('type', '-')} | {f.get('name') or '-'} | "
                f"{f.get('id') or '-'} | {detail or '-'} |"
            )
        lines.append("")

    if info["buttons"]:
        lines += ["Buttons:", "", "| type | id | text |", "| --- | --- | --- |"]
        for b in info["buttons"]:
            lines.append(f"| {b['type']} | {b['id'] or '-'} | {b['text'] or '-'} |")
        lines.append("")

    if info["errors"]:
        lines += ["Error elements present on load:", ""]
        lines += [f"    {e}" for e in info["errors"]]
        lines.append("")

    if info["links"]:
        lines += ["Navigation links (first 25):", "", "| text | href |", "| --- | --- |"]
        for a in info["links"]:
            lines.append(f"| {a['text']} | {a['href']} |")
        lines.append("")

    return lines


def main() -> int:
    settings = get_settings()
    base = settings.sut.base_url

    out = [
        "# ParaBank page structure (generated)",
        "",
        "Generated by scripts/discover_ui.py against a running instance.",
        "Do not edit by hand. Re-run the script instead.",
        "",
        "Page objects in pages/ are written from this file, so no selector is guessed.",
        "",
    ]

    with sync_playwright() as pw:
        browser = pw.chromium.launch(headless=True)
        page = browser.new_page(viewport={"width": 1280, "height": 900})
        page.set_default_timeout(15000)

        log.info("Login page")
        page.goto(f"{base}/index.htm")
        out += render(page.evaluate(EXTRACT), "Login page (index.htm)")

        log.info("Registration page")
        page.goto(f"{base}/register.htm")
        out += render(page.evaluate(EXTRACT), "Registration page (register.htm)")

        log.info("Logging in as the demo customer")
        page.goto(f"{base}/index.htm")
        page.fill("input[name='username']", settings.sut.username)
        page.fill("input[name='password']", settings.sut.password)
        page.click("input[type='submit']")
        page.wait_for_load_state("networkidle")
        log.info("After login, at %s", page.url)

        out += render(page.evaluate(EXTRACT), "After login")

        for label, path in [
            ("Account overview (overview.htm)", "/overview.htm"),
            ("Transfer funds (transfer.htm)", "/transfer.htm"),
            ("Bill payment (billpay.htm)", "/billpay.htm"),
            ("Find transactions (findtrans.htm)", "/findtrans.htm"),
            ("Open new account (openaccount.htm)", "/openaccount.htm"),
        ]:
            log.info("%s", label)
            page.goto(f"{base}{path}")
            page.wait_for_load_state("networkidle")
            out += render(page.evaluate(EXTRACT), label)

        browser.close()

    OUTPUT.write_text("\n".join(out))
    log.info("Wrote %s", OUTPUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
