"""Record the table and navigation structure of ParaBank's authenticated pages.

scripts/discover_ui.py captured forms and fields. Page objects for the account
overview and transaction history also need to read data out of tables, and the
logout link has to be found before it can be clicked.

Writes docs/sut-ui-tables.md. Idempotent: re-running overwrites the file.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from playwright.sync_api import sync_playwright  # noqa: E402

from utils.config import get_settings  # noqa: E402
from utils.logger import get_logger  # noqa: E402

log = get_logger("discover_ui_tables")

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "sut-ui-tables.md"

EXTRACT = """
() => {
  const clean = (s) => (s || '').replace(/\\s+/g, ' ').trim();
  return {
    url: location.pathname,
    tables: Array.from(document.querySelectorAll('table')).map(t => ({
      id: t.id || null,
      className: t.className || null,
      headers: Array.from(t.querySelectorAll('th')).map(h => clean(h.textContent)),
      rowCount: t.querySelectorAll('tbody tr').length || t.querySelectorAll('tr').length,
      firstRow: Array.from(
        (t.querySelector('tbody tr') || t.querySelectorAll('tr')[1] || {querySelectorAll: () => []})
          .querySelectorAll('td')
      ).map(td => clean(td.textContent)).slice(0, 8)
    })),
    panelIds: Array.from(document.querySelectorAll('[id]'))
      .map(e => e.id)
      .filter(id => id && !/^[0-9a-f]{8}-[0-9a-f]{4}-/.test(id))
      .slice(0, 40),
    links: Array.from(document.querySelectorAll('a[href]'))
      .map(a => ({ text: clean(a.textContent), href: a.getAttribute('href') }))
      .filter(a => a.text)
  };
}
"""


def render(info: dict, label: str) -> list[str]:
    lines = [f"## {label}", "", f"    path: {info['url']}", ""]

    for i, t in enumerate(info["tables"]):
        lines += [
            f"### Table {i + 1}",
            "",
            f"    id:        {t['id'] or 'none'}",
            f"    class:     {t['className'] or 'none'}",
            f"    row count: {t['rowCount']}",
            "",
        ]
        if t["headers"]:
            lines += ["Headers: " + " | ".join(t["headers"]), ""]
        if t["firstRow"]:
            lines += ["First row: " + " | ".join(t["firstRow"]), ""]

    if not info["tables"]:
        lines += ["No tables on this page.", ""]

    if info["panelIds"]:
        lines += ["Authored element identifiers on the page:", "",
                  "    " + ", ".join(info["panelIds"]), ""]

    if info["links"]:
        lines += ["Links:", "", "| text | href |", "| --- | --- |"]
        for a in info["links"]:
            lines.append(f"| {a['text']} | {a['href']} |")
        lines.append("")

    return lines


def main() -> int:
    settings = get_settings()
    base = settings.sut.base_url

    out = [
        "# ParaBank tables and navigation (generated)",
        "",
        "Generated by scripts/discover_ui_tables.py against a running instance.",
        "Do not edit by hand. Re-run the script instead.",
        "",
        "Complements docs/sut-ui-elements.md, which covers forms and fields.",
        "Page objects that read data out of tables, and the logout navigation, are",
        "written from this file.",
        "",
        "Generated identifiers matching a UUID pattern are filtered out of the",
        "element identifier lists, because a selector must never be written",
        "against one. See Finding 1 in docs/sut-ui-elements.md.",
        "",
    ]

    with sync_playwright() as pw:
        browser = pw.chromium.launch(headless=True)
        page = browser.new_page(viewport={"width": 1280, "height": 900})
        page.set_default_timeout(15000)

        page.goto(f"{base}/index.htm")
        page.fill("input[name='username']", settings.sut.username)
        page.fill("input[name='password']", settings.sut.password)
        page.click("input[type='submit'][value='Log In']")
        page.wait_for_load_state("networkidle")
        log.info("Logged in, at %s", page.url)

        out += render(page.evaluate(EXTRACT), "Account overview (overview.htm)")

        first_account_link = page.locator("#accountTable a, table a").first
        if first_account_link.count():
            account_label = first_account_link.inner_text().strip()
            log.info("Opening account detail for %s", account_label)
            first_account_link.click()
            page.wait_for_load_state("networkidle")
            out += render(page.evaluate(EXTRACT), f"Account detail (account {account_label})")
        else:
            log.error("No account link found on the overview page")
            out += ["## Account detail", "", "No account link was found on the overview page.", ""]

        page.goto(f"{base}/transfer.htm")
        page.wait_for_load_state("networkidle")
        out += render(page.evaluate(EXTRACT), "Transfer funds (transfer.htm)")

        browser.close()

    OUTPUT.write_text("\n".join(out))
    log.info("Wrote %s", OUTPUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
