"""Discover the System Under Test's REST interface and write it down.

ParaBank publishes a WADL (Web Application Description Language) document, which
is an XML description of every REST resource and method it exposes. This script
fetches it, walks the nested <resource> elements to build full paths, and writes
docs/sut-endpoints.md.

The point is that the documentation is generated from the running application
rather than typed from memory. If ParaBank changes, re-running this script tells
us, instead of the documentation quietly going stale.
"""

from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import requests

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from utils.config import get_settings  # noqa: E402
from utils.logger import get_logger  # noqa: E402

log = get_logger("discover_sut")

WADL_NS = "{http://wadl.dev.java.net/2009/02}"


def collect_resources(element: ET.Element, prefix: str = "") -> list[tuple[str, list[str]]]:
    """Walk nested <resource> elements and return (full_path, [methods]) pairs."""
    found: list[tuple[str, list[str]]] = []
    for resource in element.findall(f"{WADL_NS}resource"):
        path = resource.get("path", "").strip("/")
        full = f"{prefix}/{path}".replace("//", "/") if path else prefix
        methods = sorted(
            m.get("name", "?")
            for m in resource.findall(f"{WADL_NS}method")
        )
        if methods:
            found.append((full or "/", methods))
        found.extend(collect_resources(resource, full))
    return found


def main() -> int:
    settings = get_settings()
    wadl_url = f"{settings.sut.services_url}?_wadl"
    log.info("Fetching %s", wadl_url)

    try:
        response = requests.get(wadl_url, timeout=30)
        response.raise_for_status()
    except requests.RequestException as exc:
        log.error("Could not fetch the WADL: %s", exc)
        return 1

    try:
        root = ET.fromstring(response.content)
    except ET.ParseError as exc:
        log.error("The WADL is not valid XML: %s", exc)
        return 1

    resources: list[tuple[str, list[str]]] = []
    for app_resources in root.findall(f"{WADL_NS}resources"):
        base = app_resources.get("base", "").rstrip("/")
        resources.extend(collect_resources(app_resources, ""))
        log.info("Base URL declared in the WADL: %s", base)

    if not resources:
        log.error("No resources found in the WADL")
        return 1

    resources.sort(key=lambda item: item[0])
    log.info("Discovered %d resource paths", len(resources))

    lines = [
        "# ParaBank REST endpoints (generated)",
        "",
        "Generated by scripts/discover_sut.py from the running application's WADL",
        f"({wadl_url}). Do not edit by hand. Re-run the script instead.",
        "",
        "| Path | Methods |",
        "| --- | --- |",
    ]
    for path, methods in resources:
        lines.append(f"| `{path}` | {', '.join(methods)} |")
    lines.append("")

    out = Path(__file__).resolve().parent.parent / "docs" / "sut-endpoints.md"
    out.write_text("\n".join(lines))
    log.info("Wrote %s", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
