"""Render the UAT scenarios and their execution status.

uat/scenarios.yaml is the source of truth. This validates that every scenario
references a requirement that exists, then writes docs/uat-scenarios.md.

The execution status of each scenario is recorded in the register itself, and
the document reports it exactly as recorded. A scenario marked as not executed
appears as not executed. Nothing here infers that a journey was walked because
tests covering the same ground happen to pass.
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from utils.logger import get_logger  # noqa: E402

log = get_logger("generate_uat_doc")

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTER = REPO_ROOT / "uat" / "scenarios.yaml"
REQUIREMENTS = REPO_ROOT / "requirements.yaml"
OUTPUT = REPO_ROOT / "docs" / "uat-scenarios.md"

STATUSES = ("covered by automation", "designed, not executed", "executed",
            "partially executed")


def main() -> int:
    register = yaml.safe_load(REGISTER.read_text())
    scenarios = register["scenarios"]
    requirement_ids = {r["id"] for r in
                       yaml.safe_load(REQUIREMENTS.read_text())["requirements"]}

    problems = []
    for s in scenarios:
        for field in ("id", "title", "persona", "requirements", "business_outcome",
                      "steps", "acceptance", "status"):
            if field not in s:
                problems.append(f"{s.get('id', '?')}: missing field '{field}'")
        if s.get("status") not in STATUSES:
            problems.append(f"{s.get('id')}: status must be one of {STATUSES}")
        for rid in s.get("requirements", []):
            if rid not in requirement_ids:
                problems.append(f"{s.get('id')}: unknown requirement '{rid}'")

    if problems:
        log.error("Register invalid, %d problem(s):", len(problems))
        for p in problems:
            log.error("  %s", p)
        return 1

    lines = [
        "# User Acceptance Test scenarios",
        "",
        "Generated by scripts/generate_uat_doc.py from uat/scenarios.yaml.",
        "Do not edit by hand.",
        "",
        f"Release: {register.get('release')}",
        "",
        "## What this is, and what it is not",
        "",
        " ".join(str(register["executed_by"]).split()),
        "",
        "## Execution status",
        "",
        "| Scenario | Title | Requirements | Status |",
        "| --- | --- | --- | --- |",
    ]
    for s in scenarios:
        lines.append(
            f"| {s['id']} | {s['title']} | {', '.join(s['requirements'])} | "
            f"**{s['status']}** |"
        )

    lines += [
        "",
        "### What the statuses mean",
        "",
        "    covered by automation      the journey is exercised end to end by",
        "                               automated tests that pass. Not separately",
        "                               walked by hand, and this document says so",
        "                               rather than implying a manual pass.",
        "",
        "    designed, not executed     written and reviewable, but nobody has",
        "                               performed it. No result is claimed.",
        "",
        "    executed                   performed by hand with results recorded.",
        "",
        "Recording 'covered by automation' rather than 'passed' is deliberate.",
        "Automated tests answer whether the parts work. Acceptance testing asks",
        "whether a person can accomplish the goal, and those are different questions",
        "even when the same steps are involved.",
        "",
        "## Scenarios",
        "",
    ]

    for s in scenarios:
        lines += [
            f"### {s['id']}  {s['title']}",
            "",
            f"    persona       {s['persona']}",
            f"    requirements  {', '.join(s['requirements'])}",
            f"    status        {s['status']}",
            "",
            "**Business outcome**",
            "",
            " ".join(str(s["business_outcome"]).split()),
            "",
            "**Steps**",
            "",
        ]
        lines += [f"{i}. {step}" for i, step in enumerate(s["steps"], 1)]
        lines += ["", "**Acceptance criteria**", ""]
        lines += [f"- {c}" for c in s["acceptance"]]
        if s.get("covered_by"):
            lines += ["", "**Automated coverage**", ""]
            lines += [f"- `{t}`" for t in s["covered_by"]]
        if s.get("note"):
            lines += ["", " ".join(str(s["note"]).split())]
        lines.append("")

    OUTPUT.write_text("\n".join(lines))
    counts = Counter(s["status"] for s in scenarios)
    log.info("Validated %d scenario(s): %s", len(scenarios), dict(counts))
    log.info("Wrote %s", OUTPUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
