"""Generate docs/requirements.md from requirements.yaml.

requirements.yaml is the single source of truth. This script renders it as
readable documentation so the two can never disagree. The same YAML file feeds
the traceability matrix in Phase 2C.

Also validates the register: unique identifiers, known areas, required fields
and allowed values. Exit code 1 on any problem, so a malformed register fails
the pipeline rather than producing a quietly wrong document.
"""

from __future__ import annotations

import sys
from collections import Counter, defaultdict
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from utils.logger import get_logger  # noqa: E402

log = get_logger("generate_requirements_doc")

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTER = REPO_ROOT / "requirements.yaml"
OUTPUT = REPO_ROOT / "docs" / "requirements.md"

REQUIRED_FIELDS = ("id", "area", "title", "detail", "priority", "source", "verification")
ALLOWED_SOURCES = ("observed", "derived", "assumed")
ALLOWED_PRIORITIES = ("Critical", "High", "Medium", "Low")

SOURCE_MEANING = {
    "observed": "verified directly against the running application in Phase 1",
    "derived": "standard banking behaviour any reasonable specification includes",
    "assumed": "expected but unconfirmed; the test will settle it",
}


def validate(register: dict) -> list[str]:
    problems: list[str] = []
    areas = register.get("areas", {})
    seen: set[str] = set()

    for req in register.get("requirements", []):
        rid = req.get("id", "<missing id>")
        for field in REQUIRED_FIELDS:
            if field not in req:
                problems.append(f"{rid}: missing field '{field}'")
        if rid in seen:
            problems.append(f"{rid}: duplicate identifier")
        seen.add(rid)
        if req.get("area") not in areas:
            problems.append(f"{rid}: unknown area '{req.get('area')}'")
        if req.get("source") not in ALLOWED_SOURCES:
            problems.append(f"{rid}: source must be one of {ALLOWED_SOURCES}")
        if req.get("priority") not in ALLOWED_PRIORITIES:
            problems.append(f"{rid}: priority must be one of {ALLOWED_PRIORITIES}")
        if not isinstance(req.get("verification"), list) or not req.get("verification"):
            problems.append(f"{rid}: verification must be a non-empty list")
    return problems


def render(register: dict) -> str:
    reqs = register["requirements"]
    areas = register["areas"]

    by_area: dict[str, list[dict]] = defaultdict(list)
    for req in reqs:
        by_area[req["area"]].append(req)

    source_counts = Counter(r["source"] for r in reqs)
    priority_counts = Counter(r["priority"] for r in reqs)

    lines = [
        "# Requirements",
        "",
        "Generated by scripts/generate_requirements_doc.py from requirements.yaml.",
        "Do not edit by hand. Edit the YAML register and regenerate.",
        "",
        f"Release: {register.get('release', 'unspecified')}  ",
        f"System Under Test: {register.get('system_under_test', 'unspecified')}",
        "",
        f"Total requirements: {len(reqs)}",
        "",
        "## Where these requirements come from",
        "",
        "ParaBank is a demonstration application with no published specification, so",
        "every requirement records its origin. This matters when a test fails: an",
        "assumed requirement that fails may be a defect in the application, or it may",
        "be a wrong assumption on our part. Recording the difference up front stops",
        "assumptions being reported as defects.",
        "",
        "| Source | Meaning | Count |",
        "| --- | --- | --- |",
    ]
    for source in ALLOWED_SOURCES:
        lines.append(f"| {source} | {SOURCE_MEANING[source]} | {source_counts.get(source, 0)} |")

    lines += [
        "",
        "## Priority distribution",
        "",
        "| Priority | Count |",
        "| --- | --- |",
    ]
    for priority in ALLOWED_PRIORITIES:
        lines.append(f"| {priority} | {priority_counts.get(priority, 0)} |")

    lines += ["", "## Requirements by area", ""]

    for code, area_name in areas.items():
        area_reqs = by_area.get(code, [])
        if not area_reqs:
            continue
        lines += [
            f"### {code} - {area_name}",
            "",
            "| ID | Title | Priority | Source | Verified by |",
            "| --- | --- | --- | --- | --- |",
        ]
        for req in area_reqs:
            verified = ", ".join(req["verification"])
            lines.append(
                f"| {req['id']} | {req['title']} | {req['priority']} | {req['source']} | {verified} |"
            )
        lines.append("")
        for req in area_reqs:
            detail = " ".join(str(req["detail"]).split())
            lines.append(f"**{req['id']}** {detail}")
            lines.append("")

    return "\n".join(lines)


def main() -> int:
    if not REGISTER.exists():
        log.error("Register not found: %s", REGISTER)
        return 1

    register = yaml.safe_load(REGISTER.read_text())

    problems = validate(register)
    if problems:
        log.error("Register is invalid, %d problem(s):", len(problems))
        for problem in problems:
            log.error("  %s", problem)
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(register))
    log.info("Validated %d requirements", len(register["requirements"]))
    log.info("Wrote %s", OUTPUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
