"""Render test-cases/*.yaml into readable markdown, and validate them.

The YAML files are the source of truth. This script renders each one as a
markdown document so the two can never disagree, and validates that every case
is complete and references a requirement that actually exists.

Exit code 1 on any problem, so a malformed test case fails the pipeline rather
than producing a quietly wrong document.
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from utils.logger import get_logger  # noqa: E402

log = get_logger("generate_test_cases_doc")

REPO_ROOT = Path(__file__).resolve().parent.parent
CASE_DIR = REPO_ROOT / "test-cases"
REGISTER = REPO_ROOT / "requirements.yaml"

REQUIRED = ("id", "requirement", "title", "technique", "layer",
            "preconditions", "test_data", "steps", "expected", "priority",
            "automation", "phase")
TECHNIQUES = ("Equivalence Partitioning", "Boundary Value Analysis",
              "Decision Table Testing", "State Transition Testing",
              "Pairwise Testing", "Negative Testing")
AUTOMATION = ("automated", "planned", "manual", "deferred")
PRIORITIES = ("Critical", "High", "Medium", "Low")


def load_requirement_ids() -> set[str]:
    register = yaml.safe_load(REGISTER.read_text())
    return {r["id"] for r in register["requirements"]}


def validate(cases: list[dict], req_ids: set[str], seen: set[str]) -> list[str]:
    problems = []
    for case in cases:
        cid = case.get("id", "<missing id>")
        for field in REQUIRED:
            if field not in case:
                problems.append(f"{cid}: missing field '{field}'")
        if cid in seen:
            problems.append(f"{cid}: duplicate identifier")
        seen.add(cid)
        if case.get("requirement") not in req_ids:
            problems.append(f"{cid}: unknown requirement '{case.get('requirement')}'")
        if case.get("technique") not in TECHNIQUES:
            problems.append(f"{cid}: technique must be one of {TECHNIQUES}")
        if case.get("automation") not in AUTOMATION:
            problems.append(f"{cid}: automation must be one of {AUTOMATION}")
        if case.get("priority") not in PRIORITIES:
            problems.append(f"{cid}: priority must be one of {PRIORITIES}")
        if not isinstance(case.get("steps"), list) or not case.get("steps"):
            problems.append(f"{cid}: steps must be a non-empty list")
        if case.get("automation") == "automated" and "automated_test" not in case:
            problems.append(f"{cid}: automation is 'automated' but no automated_test is named")
    return problems


def render(suite: dict, source_name: str) -> str:
    cases = suite["test_cases"]
    lines = [
        f"# Test cases: {suite['suite']}",
        "",
        f"Generated by scripts/generate_test_cases_doc.py from test-cases/{source_name}.",
        "Do not edit by hand. Edit the YAML and regenerate.",
        "",
        " ".join(str(suite.get("description", "")).split()),
        "",
        f"Cases in this suite: {len(cases)}",
        "",
        "| ID | Requirement | Title | Technique | Priority | Automation |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for c in cases:
        lines.append(
            f"| {c['id']} | {c['requirement']} | {c['title']} | "
            f"{c['technique']} | {c['priority']} | {c['automation']} |"
        )
    lines.append("")

    for c in cases:
        lines += [
            f"## {c['id']} {c['title']}",
            "",
            f"**Requirement** {c['requirement']}  ",
            f"**Technique** {c['technique']}  ",
            f"**Layer** {c['layer']}  ",
            f"**Priority** {c['priority']}  ",
            f"**Automation** {c['automation']}"
            + (f" ({c['automated_test']})" if c.get("automated_test") else "")
            + f"  ",
            f"**Introduced in phase** {c['phase']}",
            "",
            f"**Preconditions** {' '.join(str(c['preconditions']).split())}",
            "",
            f"**Test data** {' '.join(str(c['test_data']).split())}",
            "",
            "**Steps**",
            "",
        ]
        for i, step in enumerate(c["steps"], 1):
            lines.append(f"{i}. {' '.join(str(step).split())}")
        lines += ["", f"**Expected result** {' '.join(str(c['expected']).split())}", ""]

    return "\n".join(lines)


def main() -> int:
    if not REGISTER.exists():
        log.error("Requirements register not found: %s", REGISTER)
        return 1

    req_ids = load_requirement_ids()
    sources = sorted(CASE_DIR.glob("*.yaml"))
    if not sources:
        log.error("No test case files found in %s", CASE_DIR)
        return 1

    seen: set[str] = set()
    all_problems: list[str] = []
    all_cases: list[dict] = []

    for path in sources:
        suite = yaml.safe_load(path.read_text())
        cases = suite.get("test_cases", [])
        problems = validate(cases, req_ids, seen)
        all_problems.extend(problems)
        all_cases.extend(cases)
        if not problems:
            out = path.with_suffix(".md")
            out.write_text(render(suite, path.name))
            log.info("%-24s %3d cases -> %s", path.name, len(cases), out.name)

    if all_problems:
        log.error("Validation failed, %d problem(s):", len(all_problems))
        for p in all_problems:
            log.error("  %s", p)
        return 1

    log.info("Total test cases: %d", len(all_cases))
    log.info("By technique : %s", dict(Counter(c["technique"] for c in all_cases)))
    log.info("By automation: %s", dict(Counter(c["automation"] for c in all_cases)))
    log.info("By priority  : %s", dict(Counter(c["priority"] for c in all_cases)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
