"""Generate the Requirements Traceability Matrix.

The traceability matrix is the table that answers the only question that
matters at release time: is every requirement covered by a test, did that test
run, and what did it find.

It links, in one chain:

    requirement -> test case -> automation -> defect -> result

At this stage of the project no test has been executed and no defect has been
raised, so the result and defect columns read "not executed" and "none". They
are populated from real data in Phase 6 and Phase 7. Nothing is invented here.

Exit code 1 if any requirement has no test case at all, so a coverage gap fails
the pipeline rather than sitting unnoticed in a document.
"""

from __future__ import annotations

import sys
from collections import Counter, defaultdict
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from utils.logger import get_logger  # noqa: E402

log = get_logger("generate_rtm")

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTER = REPO_ROOT / "requirements.yaml"
CASE_DIR = REPO_ROOT / "test-cases"
OUTPUT = REPO_ROOT / "docs" / "requirements-traceability-matrix.md"

NOT_EXECUTED = "not executed"
NO_DEFECT = "none"


def load_cases() -> list[dict]:
    cases: list[dict] = []
    for path in sorted(CASE_DIR.glob("*.yaml")):
        suite = yaml.safe_load(path.read_text())
        for case in suite.get("test_cases", []):
            case["_suite"] = suite.get("suite", path.stem)
            cases.append(case)
    return cases


def main() -> int:
    if not REGISTER.exists():
        log.error("Requirements register not found: %s", REGISTER)
        return 1

    register = yaml.safe_load(REGISTER.read_text())
    requirements = register["requirements"]
    areas = register["areas"]
    cases = load_cases()

    by_requirement: dict[str, list[dict]] = defaultdict(list)
    for case in cases:
        by_requirement[case["requirement"]].append(case)

    req_ids = {r["id"] for r in requirements}
    orphans = sorted({c["requirement"] for c in cases} - req_ids)
    uncovered = sorted(r["id"] for r in requirements if not by_requirement.get(r["id"]))

    covered = len(requirements) - len(uncovered)
    coverage_pct = round(100 * covered / len(requirements), 1) if requirements else 0.0

    automation_counts = Counter(c["automation"] for c in cases)
    technique_counts = Counter(c["technique"] for c in cases)

    lines = [
        "# Requirements Traceability Matrix",
        "",
        "Generated by scripts/generate_rtm.py from requirements.yaml and test-cases/*.yaml.",
        "Do not edit by hand.",
        "",
        f"Release: {register.get('release', 'unspecified')}  ",
        f"System Under Test: {register.get('system_under_test', 'unspecified')}",
        "",
        "## What this table is for",
        "",
        "It links each requirement to the test cases that cover it, the automation",
        "that runs them, any defect they found, and the result. A requirement with no",
        "test case is a coverage gap. A test case with no requirement is a test nobody",
        "asked for.",
        "",
        "## Honesty note",
        "",
        "No test has been executed yet and no defect has been raised, so the result and",
        "defect columns read 'not executed' and 'none'. They are filled from real",
        "execution data in Phase 6 and Phase 7. A traceability matrix that shows results",
        "which never happened is worse than no matrix at all.",
        "",
        "Coverage here means a requirement has at least one test case. It does not mean",
        "the requirement is fully verified.",
        "",
        "## Summary",
        "",
        f"| Measure | Value |",
        f"| --- | --- |",
        f"| Requirements | {len(requirements)} |",
        f"| Test cases | {len(cases)} |",
        f"| Requirements with at least one test case | {covered} |",
        f"| Requirements with no test case | {len(uncovered)} |",
        f"| Coverage | {coverage_pct} percent |",
        "",
        "### Test cases by automation status",
        "",
        "| Status | Count |",
        "| --- | --- |",
    ]
    for status in ("automated", "planned", "manual", "deferred"):
        lines.append(f"| {status} | {automation_counts.get(status, 0)} |")

    lines += ["", "### Test cases by design technique", "", "| Technique | Count |", "| --- | --- |"]
    for technique, count in sorted(technique_counts.items(), key=lambda kv: -kv[1]):
        lines.append(f"| {technique} | {count} |")

    lines += ["", "## Matrix", ""]

    for code, area_name in areas.items():
        area_reqs = [r for r in requirements if r["area"] == code]
        if not area_reqs:
            continue
        lines += [
            f"### {code} - {area_name}",
            "",
            "| Requirement | Priority | Source | Test case | Technique | Automation | Defect | Result |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
        for req in area_reqs:
            matched = by_requirement.get(req["id"], [])
            if not matched:
                lines.append(
                    f"| {req['id']} | {req['priority']} | {req['source']} | "
                    f"**NO TEST CASE** | - | - | - | - |"
                )
                continue
            for case in matched:
                automation = case["automation"]
                if case.get("automated_test"):
                    automation = f"{automation}: `{case['automated_test']}`"
                lines.append(
                    f"| {req['id']} | {req['priority']} | {req['source']} | "
                    f"{case['id']} {case['title']} | {case['technique']} | "
                    f"{automation} | {NO_DEFECT} | {NOT_EXECUTED} |"
                )
        lines.append("")

    if uncovered:
        lines += ["## Coverage gaps", "",
                  "These requirements have no test case and must be addressed:", ""]
        lines += [f"- {rid}" for rid in uncovered]
        lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines))

    log.info("Requirements: %d, test cases: %d", len(requirements), len(cases))
    log.info("Coverage: %s percent (%d covered, %d uncovered)", coverage_pct, covered, len(uncovered))
    log.info("Wrote %s", OUTPUT)

    if orphans:
        log.error("Test cases reference unknown requirements: %s", ", ".join(orphans))
        return 1
    if uncovered:
        log.error("Requirements with no test case: %s", ", ".join(uncovered))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
